# Generated by Django 5.0.1 on 2024-03-26 03:41

import django.core.validators
import phonenumber_field.modelfields
import profile_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_club', models.BooleanField(default=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone_number')),
                ('year', models.PositiveIntegerField(blank=True, default=2024, validators=[django.core.validators.MinValueValidator(1980), profile_api.models.max_value_year], verbose_name='year')),
                ('bio', models.CharField(blank=True, max_length=500, verbose_name='bio')),
                ('shirt_size', models.CharField(blank=True, choices=[("Women's XS", 'WOMEN_XS'), ("Women's S", 'WOMEN_S'), ("Women's M", 'WOMEN_M'), ("Women's L", 'WOMEN_L'), ("Women's XL", 'WOMEN_XL'), ("Women's XXL", 'WOMEN_XXL'), ("Men's XS", 'MEN_XS'), ("Men's S", 'MEN_S'), ("Men's M", 'MEN_M'), ("Men's L", 'MEN_L'), ("Men's XL", 'MEN_XL'), ("Men's XXL", 'MEN_XXL')], max_length=12, verbose_name='shirt_size')),
            ],
        ),
    ]
