# Generated by Django 5.0.1 on 2024-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('WOMEN_XS', "Women's XS"), ('WOMEN_S', "Women's S"), ('WOMEN_M', "Women's M"), ('WOMEN_L', "Women's L"), ('WOMEN_XL', "Women's XL"), ('WOMEN_XXL', "Women's XXL"), ('MEN_XS', "Men's XS"), ('MEN_S', "Men's S"), ('MEN_M', "Men's M"), ('MEN_L', "Men's L"), ('MEN_XL', "Men's XL"), ('MEN_XXL', "Men's XXL")], max_length=12, verbose_name='shirt_size'),
        ),
    ]
