# Generated by Django 5.0.1 on 2024-03-25 20:59

import django.core.validators
import user_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1980), user_api.models.max_value_year], verbose_name='year'),
        ),
    ]
