# Generated by Django 5.0.1 on 2024-04-01 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/images')),
                ('description', models.TextField(blank=True)),
                ('background_color', models.CharField(blank=True, default='#FFFFFF', max_length=7)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clubs', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='joined_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
